spring:
  application:
    name: test-integration-service
  datasource:
        url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:country_db}?createDatabaseIfNotExist=true&useSSL=false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

# Custom SOAP Configuration
soap:
  api:
    url: http://webservices.oorsprong.org/websamples.countryinfo/CountryInfoService.wso

# Management & Health Checks
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always